# Custom Language File for Launcher Customizer

[ejs.app]
title = "븜타이쿤"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/B-tycoon"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/B-tycoon"
supportLink = "https://github.com/CustomLauncherLab/B-tycoon/issues"

[ejs.welcome]
welcomeHeader = "븜타이쿤"
welcomeDescription = ""
welcomeDescCTA = ""
